name: CD

on: 
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: cd using ssh command
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.ERP_PUPUK_STAGING }}
          port: 22
          script: |
            cd ~/custom-idurar-erp-crm/
            git pull origin develop
            git status
            npm install --onlyprod
            pm2 restart server
